version: '3'
services:
  app:
    build:
      context: .
    #image: codeigniter/nginx-php-fpm:7
    ports:
      - '80:80'
    environment:
      - VIRTUAL_HOST=localhost
    #network_mode: "host"
    volumes:
      - '.:/var/www/html'
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211:11211"
